on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: install yarn, check version
      run: |
        npm install --global yarn
        yarn --version

    - name: yarn install, build, and test
      run: |
        yarn install
        yarn tsc
        yarn build:all
        yarn test:all
    
    - name: build image
      run: yarn build-image --tag oleo-backstage:1.0.0

    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
    
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        # docker build -f ./packages/backend/Dockerfile -t local/example .
        echo -n "verifying images:"
        docker images

    - name: render K8s manifests
      run: envsubst < ./deploy-config/everything.template.yaml > everything.yaml

    - name: Deploy to minikube
      run:
        kubectl apply -f everything.yaml

    - name: Test service URLs
      run: |
        minikube service list
        minikube service backstage --url -n backstage
        echo "------------------opening the service------------------"
        curl $(minikube service backstage --url -n backstage)